# Generated by Home Manager.
# See https://sw.kovidgoyal.net/kitty/conf.html
font_family JetBrainsMono Nerd Font Mono font_size 13

include
/nix/store/4hm09yzmmhy7gyg4lbfz5cqsk6mmda36-kitty-themes-0-unstable-2024-08-14/share/kitty-themes/themes/Dracula.conf

# Shell integration is sourced and configured manually
shell_integration no-rc

background_blur 20 background_opacity 0.96 confirm_os_window_close 0
copy_on_select no cursor_beam_thickness 1.8 cursor_blink_interval 0.7
cursor_shape beam cursor_trail 80 cursor_trail_decay 8.0e-2 0.25 detect_urls yes
enable_audio_bell no input_delay 2 repaint_delay 8 scrollback_lines 10000
tab_bar_edge bottom tab_bar_min_tabs 2 tab_bar_style powerline
tab_powerline_style round url_style curly window_margin_width 8
window_padding_width 12

# Keybindings
map ctrl + shift + t new_tab map ctrl + shift + q close_tab map ctrl + shift
+ w close_os_window map ctrl + shift + enter new_window

map ctrl + shift + equal change_font_size all + 2.0 map ctrl + shift
+ minus change_font_size all - 2.0 map ctrl + shift + 0 change_font_size all 0

map ctrl + l clear_terminal to_cursor_scroll active map ctrl + shift
+ k clear_terminal scrollback active

